# Generated by Django 3.2.11 on 2022-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('compound', models.CharField(max_length=700, verbose_name='Состав')),
                ('add_jalapeno', models.IntegerField(default=0, verbose_name='Добавка "Халапеньо"')),
                ('add_ched', models.IntegerField(default=0, verbose_name='Добавка "Сыр чеддер"')),
                ('add_crispy_onion', models.IntegerField(default=0, verbose_name='Добавка "Хурстящий лук"')),
                ('add_bacon', models.IntegerField(default=0, verbose_name='Добавка "Бекон"')),
                ('add_onion', models.IntegerField(default=0, verbose_name='Дабавка "Маринованный лук"')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Бургер',
                'verbose_name_plural': 'Бургеры',
            },
        ),
    ]
