# Generated by Django 3.2.11 on 2022-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='burgers_image'),
        ),
        migrations.AddField(
            model_name='burger',
            name='slug',
            field=models.CharField(default=1, max_length=100, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
