# Generated by Django 3.2.11 on 2022-09-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220901_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesfororder',
            options={'verbose_name': 'Блюдо для заказа', 'verbose_name_plural': 'Блюда для заказов'},
        ),
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Соусы', 'Соусы'), ('Шашлык', 'Шашлык'), ('Напитки', 'Напитки'), ('Закуски', 'Закуски')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='category',
            field=models.CharField(choices=[('Бургеры', 'Бургеры'), ('Шаверма/Роллы', 'Шаверма/Роллы')], max_length=300, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ToppingForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.topping')),
            ],
            options={
                'verbose_name': 'Топинг для заказа',
                'verbose_name_plural': 'Топинги для заказов',
            },
        ),
        migrations.AlterField(
            model_name='dishesfororder',
            name='toppings',
            field=models.ManyToManyField(to='website.ToppingForOrder'),
        ),
    ]
