# Generated by Django 3.2.11 on 2022-09-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220902_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Шашлык', 'Шашлык'), ('Напитки', 'Напитки'), ('Соусы', 'Соусы'), ('Закуски', 'Закуски')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='toppingfororder',
            name='amount',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='toppingfororder',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
