# Generated by Django 3.2.11 on 2022-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220904_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Напитки', 'Напитки'), ('Закуски', 'Закуски'), ('Соусы', 'Соусы'), ('Шашлык', 'Шашлык')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='toppingfororder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
