# Generated by Django 3.2.11 on 2022-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220904_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='extramenu',
            name='slug',
            field=models.CharField(default='xxxxxxxxxxxxx', max_length=300, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishesfororder',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Шашлык', 'Шашлык'), ('Закуски', 'Закуски'), ('Соусы', 'Соусы'), ('Напитки', 'Напитки')], max_length=300, verbose_name='Категория'),
        ),
    ]
