# Generated by Django 3.2.11 on 2022-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220907_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес, г'),
        ),
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Закуски', 'Закуски'), ('Соусы', 'Соусы'), ('Напитки', 'Напитки'), ('Шашлык', 'Шашлык')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='category',
            field=models.CharField(choices=[('Бургеры', 'Бургеры'), ('Закуски', 'Закуски'), ('Напитки', 'Напитки'), ('Соусы', 'Соусы'), ('Шаверма/Роллы', 'Шаверма/Роллы'), ('Шашлык', 'Шашлык')], max_length=300, verbose_name='Категория'),
        ),
    ]
