# Generated by Django 3.2.11 on 2022-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220930_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Соусы', 'Соусы'), ('Шашлык', 'Шашлык'), ('Закуски', 'Закуски'), ('Напитки', 'Напитки')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='category',
            field=models.CharField(choices=[('Шаверма/Роллы', 'Шаверма/Роллы'), ('Закуски', 'Закуски'), ('Бургеры', 'Бургеры'), ('Соусы', 'Соусы'), ('Напитки', 'Напитки'), ('Шашлык', 'Шашлык')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='compound',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Состав'),
        ),
    ]
