# Generated by Django 3.2.11 on 2022-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20221002_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramenu',
            name='category',
            field=models.CharField(choices=[('Закуски', 'Закуски'), ('Соусы', 'Соусы'), ('Напитки', 'Напитки'), ('Шашлык', 'Шашлык')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='category',
            field=models.CharField(choices=[('Соусы', 'Соусы'), ('Напитки', 'Напитки'), ('Шашлык', 'Шашлык'), ('Бургеры', 'Бургеры'), ('Закуски', 'Закуски'), ('Шаверма/Роллы', 'Шаверма/Роллы')], max_length=300, verbose_name='Категория'),
        ),
    ]
